version: "3.3"

networks:
  private:

services:
  rabbit:
    image: rabbitmq:3-management-alpine
    networks:
      - private
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass
  
  queue_metadata:
    image: antuanuran/pika:latest
    restart: always
    networks:
      - private
    depends_on:
      - rabbit
    #command: "python queue_listener.py"

  start_poling:
    image: antuanuran/pika:latest
    restart: always
    networks:
      - private
    depends_on:
      - queue_metadata
    command: "python start_bot.py"

#  queue_tg:
#    image: antuanuran/pika:latest
#    restart: always
#    networks:
#      - private
#    depends_on:
#      - start_poling
#    command: "python queue_telegram.py"
